remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: true
  month: false
  week: false
  24 hours: false

positions:
  - Product Designer
  - UX Designer
  - UI Designer

locations:
  - United States
  - Remote
  - San Francisco Bay Area
  - San Francisco
  - Greater Seattle Metropolitan Area
  - New york city metropolitan area
  - Los Angeles
  - San Diego
  - Bay Area
  - Oakland
  - San Jose
  - Manhattan
  - New York
  - Brooklyn
  - Queens
  - Jersey City
  - Newark

distance: 100

companyBlacklist:
  - 

titleBlacklist: